# Generated by Django 3.0.6 on 2020-10-30 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smaterials', '0002_auto_20201030_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smaterials',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='smaterials',
            name='image',
        ),
    ]
