# Generated by Django 3.0.6 on 2020-10-30 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smaterials', '0003_auto_20201030_1811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smaterials',
            old_name='title',
            new_name='title1',
        ),
    ]
