# Generated by Django 3.0.6 on 2020-11-13 06:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('smaterials', '0005_coursename'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursename',
            name='urlname',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
