# Generated by Django 3.0.6 on 2021-01-01 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smaterials', '0006_coursename_urlname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SMaterials',
        ),
    ]
