# Generated by Django 3.0.6 on 2020-10-30 08:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/')),
                ('title', models.CharField(max_length=200)),
                ('detail', models.TextField(max_length=500)),
                ('expiry_date', models.TextField(max_length=200)),
                ('updated_date', models.DateTimeField(default=datetime.datetime(2020, 10, 30, 14, 14, 19, 756948))),
            ],
        ),
    ]
