# Generated by Django 3.0.6 on 2020-10-30 08:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_details',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 30, 14, 14, 40, 842499)),
        ),
    ]
