# Generated by Django 3.0.6 on 2020-10-30 12:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201030_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_details',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 30, 17, 43, 14, 345247)),
        ),
    ]
