# Generated by Django 3.0.6 on 2020-10-30 12:29

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201030_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_details',
            name='stitle',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course_details',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 30, 17, 59, 38, 757018)),
        ),
    ]
