# Generated by Django 3.0.6 on 2020-10-30 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201030_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_details',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 30, 21, 35, 38, 51690)),
        ),
    ]
