# Generated by Django 3.0.6 on 2020-10-30 16:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201030_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_details',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 30, 21, 53, 2, 153086)),
        ),
    ]
