# Generated by Django 3.0.6 on 2021-01-01 15:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210101_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_details',
            name='updated_date',
            field=models.DateField(default=datetime.datetime(2021, 1, 1, 20, 38, 57, 17876)),
        ),
    ]
